name: Deploy to gh-pages branch

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node (si usás herramientas que lo requieren, si no podés borrar este paso)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Crear carpeta de salida
        run: mkdir -p dist && cp -r * dist || true

      - name: Deploy a GitHub Pages (branch gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
